### ISSUE TITLE
after upgrading to 0.15.1 project not building anymore, build.zig needs update?

### ISSUE THREAD

**Issue by silviogames** [G3bE/raylib-zig#277]
My game as well as a fresh project created with the most recent commit won't build and throw this:
```
build.zig:38:56: error: no field named 'root_source_file' in struct 'Build.ExecutableOptions'
    const exe = b.addExecutable(.{ .name = "Project", .root_source_file = b.path("src/main.zig"), .optimize = optimize, .target = target });
                                                       ^~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:771:31: note: struct declared here
pub const ExecutableOptions = struct {
                              ^~~~~~
referenced by:
    runBuild__anon_21153: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/std/Build.zig:2215:44
    main: /opt/homebrew/Cellar/zig/0.15.1/lib/zig/compiler/build_runner.zig:366:29
    4 reference(s) hidden; use '-freference-trace=6' to see all references
```
I compared version 0.14.1 with 0.15.1 and saw this in 0.14.1
https://github.com/ziglang/zig/blob/d03a147ea0a590ca711b3db07106effc559b0fc6/lib/std/Build.zig#L708C5-L709C40 :
```
/// Deprecated; prefer populating `root_module`.
    root_source_file: ?LazyPath = null,
```

thank you for your work, I really appreciate the bindings :))

**Comment by Not-Nik** [comment]
This is about your build.zig, not raylib-zig's. The project templates have been updated.

**Comment by silviogames** [comment]
okay nevermind, I was sure to have cloned the newest commit but apparently I did not and now it builds.
